name: ares_flutter

description: Aplicativo Flutter para gerenciamento de agendamentos de cirurgias.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  auto_route: ^7.8.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true 